'''
Tick Tock
The time.sleep() function, which pauses program execution for a specified amount of time, is useful, but rather plain. Let’s write our own tick
_tock(seconds) function that also pauses for seconds amount of time but
prints Tick... and Tock... each second while waiting.
For example, calling the function from the interactive shell should look
like this (with a one-second pause after each line of output):
>>> tick_tock(4)
Tick...
Tock...
Tick...
Tock...
>>> tick_tock(3)
Tick...
Tock...
Tick...
You may assume that the seconds parameter always has a positive integer
argument. Keep in mind that if the argument for seconds is odd, the last
thing the function should print is Tick...
'''